name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: shiv1996
          password: dckr_pat_vhqyeSVyzuuvTWJEYNNzqmpB0-E
      - name: Build the hello-docker Docker image
        run: |
           pwd
           ls -al
           docker build . --file Dockerfile --tag shiv1996/hello-world:test
           docker push shiv1996/hello-world:test

