name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Build the hello-docker Docker image
        working-directory: ../
        run: |
           pwd
           ls -al
           docker build . --file Dockerfile --tag shiv1996/hello-world:latest
           docker push shiv1996/hello-world:latest

