name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Build the hello-docker Docker image
        run: |
           pwd
           ls -al
           docker build /home/runner/work/. --tag shiv1996/hello-world:latest
           docker push shiv1996/hello-world:latest

