name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Build the hello-docker Docker image
        run: |
           pwd
           ls -al
           docker login --username=shiv1996 --email=naikshiv41@gmail.com password:tarakmehta134!
           docker build . --file Dockerfile --tag shiv1996/hello-world:test
           docker push shiv1996/hello-world:test

